### ISSUE TITLE
Explain

### ISSUE THREAD

**Issue by gilbert76** [jimhigson/ring-api#10]
Hello,

Can someone explain to me how I can use and execute this code? A simple example would suffice.

Very much thanks. :-)

**Comment by TheOriginalMrWolf** [comment]
Did you look in the examples directory?

**Comment by gilbert76** [comment]
Yes i see it, and i try to execute this code, but i get every time error codes.

**Comment by TheOriginalMrWolf** [comment]
Ummmm.... sorry, my crystal ball is still at the shop getting fixed...

What sort of errors are you seeing?

**Comment by gilbert76** [comment]
pi@raspberrypi:~/modules/tmp/ring-api/examples $ node example-script.js
module.js:540
    throw err;
    ^

Error: Cannot find module 'node-ask'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/modules/tmp/ring-api/examples/example-script.js:13:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by TheOriginalMrWolf** [comment]
```
Error: Cannot find module 'node-ask'
```
So install module "node-ask".  eg: npm i node-ask

Once you've got that sorted, and set up your username/password, then it should execute properly.

However, I expect you'll then run into issue #9 - Can't obtain oauth token - client not authorised...

**Comment by jimhigson** [comment]
I put node-ask into the dev dependencies to make the example script easier to run. If you install 3.0.4 from npm it'll get that for you now.

Issue 9 is also fixed so the example script should still work. It's quite geared towards the devices that I happen to have here, but should work for everyone.

**Comment by gilbert76** [comment]
Very much thanks, now it works very nice.  :-))))

Now I want to try to save a live Stream when the doorbell bell. You have any idea?
The most dificult is to

**Comment by jimhigson** [comment]
I know some people have done this but it isn’t trivial. You’ll need to start with a SIP client since the live streams are just SIP calls. I haven’t done it myself though so can’t advise further.
