### ISSUE TITLE
Can't get endpoint --> "not authorized"

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [jimhigson/ring-api#11]
Hi,

Whilst the fix to issue #9 worked perfectly yesterday, it looks like Ring have now jumped on that as well.

Today (using example-script.js again) I'm getting:
```
 Error: problem GETing endpoint https://api.ring.com/clients_api/dings/active?burst=false --caused-by-> Request to ring API at https://api.ring.com/clients_api/dings/active?burst=false failed with "not authorized" --caused-by-> Request failed with status code 401
```

Bit of a bummer :(

**Comment by TheOriginalMrWolf** [comment]
Oh, and further down in the log I'm also seeing:
```
(node:5111) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:5111) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Which looks like it might need a bit of work as well in order to stop the Node.js process from terminating...

Thanks again!!!

**Comment by ke6jjj** [comment]
I'm having the same issue.

**Comment by ke6jjj** [comment]
Forgot to leave my version info: I'm running 3.0.5, installed via npm 3.4 hours ago.

**Comment by jimhigson** [comment]
Urgh! They’re hardly friendly to third parties at ring!

**Comment by jimhigson** [comment]
> Which looks like it might need a bit of work as well in order to stop the Node.js process from terminating...

Oh I see, it's the polling that's erroring. That's a tricky one to know what to do with since there's no outward-facing promise to reject. Best way might be to just take an error handler from the user.

**Comment by jimhigson** [comment]
as a quick fix, I'll make polling only start once we have a valid token, that should deal with the large majority of these cases

**Comment by jimhigson** [comment]
My ability to intercept traffic is gone on my existing setup. Will hopefully see [if these guys know how to still do it](https://github.com/davglass/doorbot/issues/28).

**Comment by TheOriginalMrWolf** [comment]
Is there a substantial difference between how ring-api and doorbot authenticate, as doorbot still works?

**Comment by jimhigson** [comment]
Looking at the code, I can't see any real difference. Must be something quite subtle.

**Comment by TheOriginalMrWolf** [comment]
Could it be timing?  I notice doorbot waits a couple of seconds after authenticating before it tries to use the token (waiting for it to propogate -- maybe the token gets 'cancelled' if it's used too quickly???).  

Couldn't see anything similar in your code???

**Comment by jimhigson** [comment]
Ok, fixed. Get v3.0.6 from npm.

I haven't seen the lack of a pause create a problem thus far, but will add one in if it turns out to be needed.

**Comment by TheOriginalMrWolf** [comment]
Works - awesome, thanks!!
