### ISSUE TITLE
Any other API methods.

### ISSUE THREAD

**Issue by FozzieHi** [jimhigson/ring-api#2]
Do you have a Docs page that we can view all of the API methods, is there any ones to turn lights on like in doorbot's API, thanks.

**Comment by FozzieHi** [comment]
Nevermind! saw the lights on method, still wondering about the docs page?

**Comment by jimhigson** [comment]
There’s the main README that has all the methods and a separate example
script. Other than that there isn’t other documentation, but between them
they cover all currently available methods. Let me know if there’s anything
missing that you need.
