### ISSUE TITLE
Unexpected Identifier

### ISSUE THREAD

**Issue by jplandry908** [jimhigson/ring-api#3]
I am receiving a 'SyntaxError: Unexpected identifier' on 'reqData'  within rest-client.js for the command "const ringRequest = async reqData => {". Has anyone else received a similar error and know how to fix it All I have done was install the npm module, and added the two lines require 'ring-api' and my email/password.

**Comment by jimhigson** [comment]
Is there any chance you could post the HTTP response that you’re getting
back from ring?

**Comment by jplandry908** [comment]
I'm a newbie to node, but it appears that it is not even getting that far. It looks like that error is being produced when trying to build the request before it makes the request?

**Comment by jimhigson** [comment]
Interesting. May be a bug in the code. Do you have a stack trace?

**Comment by jimhigson** [comment]
Oh wait, which version of node do you have? If it’s complaining about async
you might have a version that doesn’t support that version of ECMAscript

**Comment by jimhigson** [comment]
Try running on the cli: ‘node —version’ and also open node (no arguments)
and type into the node prompt ‘const a = async () => {}’ and let me know
what you get

**Comment by jplandry908** [comment]
This is the trace:
const ringRequest = async reqData => {
                          ^^^^^^^
						  
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\...)

**Comment by jplandry908** [comment]
node --version
v6.11.3

**Comment by jplandry908** [comment]
FYI - The ^^^^ in the trace is actually under the 'redData'. The formatting is off when I posted it.

**Comment by jimhigson** [comment]
Ok, see the problem. Node only included async/await support on by default
since version 7.6. Is there any reason you can’t run a newer version?

If you can’t, try running node with the —harmony flag to turn on
‘experimental’ features. This isn’t needed in newer versions of node, but
async/await was considered experimental not so long ago.

I’d recommend just upgrading node though, if you can.

**Comment by jplandry908** [comment]
There is no issues upgrading node on this machine. Thank you so much for your assistance. Greatly appreciated! :)

**Comment by jplandry908** [comment]
FYI - An upgrade did indeed fix it. Thanks again!

**Comment by jimhigson** [comment]
Nice. No problem.
