### ISSUE TITLE
Node < 7.0 version - Async

### ISSUE THREAD

**Issue by jawa-the-hutt** [jimhigson/ring-api#5]
I have been struggling to get this to work with Azure Functions v1 and that is because it's currently locked in at node 6.11.2 and Node versions less than 7 don't support Async/Await.  After wrestling with getting Webpack to reach into just the 'ring-api' node_modules folder and use Babel to handle the Async/Await stuff but ignore all other folders in node_modules, I have given up.

That being said, I have forked this library and have done some minor adjustments to this library to have Babel transpile this down to something that will work in Node 6.  Would you be interested in having a Pull Request submitted that will handle the Async/Await stuff for older versions of Node and potentially older versions of Browsers as well?

I can do this via Webpack and bundle all other needed modules (Axios, etc) so that this is a self contained library in one file (about 80kb minified), or I can just use Babel and have it transpile each file in the library individually and not have it bring in anything else.  

It would then be up to the person using 'ring-api' to make sure any needed libraries that 'ring-api' uses are bundled into their app.

**Comment by jimhigson** [comment]
I’m not against it, but this sounds like quite a lot of work to get new
code working in an old version of node and I’m not seeing the cost/benefit
ratio paying off here vs just updating node.

Having said that, if there is some reason why a significant number of
people can’t update, having an old-node compatible version would make
sense.

Node 7 is very old now. 8 is the current LTS release and 10.1 is the latest
version.

Wouldn’t it be simpler to just upgrade node? Or change hosts if for some
reason your hosting is keeping you back?

Fwiw, I ‘host’ my own api here in a little app on a raspberry pi. Even that
has much more power than I actually need.

**Comment by jawa-the-hutt** [comment]
It's not a huge amount of work, but I understand what you're saying.  In this instance, the version 6 is locked in by Azure for the Azure Functions version 1 platform.  Version 2 is in preview release and will be on 8.9 LTS when it finally comes out.  

If you don't mind, keep this issue open for now and when I get some time this week or next I'll try and figure out if there is a way to do this such that the code detects the running version of node and then branches to use Babel transpiled code if it's less than 7.

From your standpoint in maintaining this long term it should all be handled by package.json scripts and webpack if that ends up getting used.  However, if this is something you just don't want to mess with maintaining or being concerned about for each update, then I completely understand and I'll fork this and use my fork until such a time that Azure Functions goes GA on Node 8.9.

**Comment by jimhigson** [comment]
Have you tried loading using something like [babel's require hook](https://babeljs.io/docs/en/babel-register.html)?

**Comment by jawa-the-hutt** [comment]
I have not. However, in the past few days, Azure Functions v2 has finally added proxies into its feature set.  This was really the only remaining reason I was still using v1.  With v2, they are moving to Node 8.9.x so we're good to close this as I'll no longer have the need to support any version of node lower than that.

Thanks!
