### ISSUE TITLE
Ring disabled session API endpoint?

### ISSUE THREAD

**Issue by michaeldimoudis** [jimhigson/ring-api#6]
I can't seem to get a new auth token, looks like Ring has changed something... 

Error is:

{
    "error": "You need to sign in or sign up before continuing."
}

However a previous token I have still works for calling the API's. I'll try help finding out how to get around this too...

**Comment by jimhigson** [comment]
Thanks for the note. The easiest way to work this out is to intercept
traffic to and from the actual iOS/Android app. In the meantime, maybe
ring-api should have some way to keep and re-use old tokens in case it
later can’t get a new one.

**Comment by will-austin** [comment]
Same here... 

> HTTPError: 401 Client Error: Unauthorized for url: https://api.ring.com/clients_api/session

**Comment by OrZidkani** [comment]
The same...

**Comment by benfysh** [comment]
I believe Ring have updated the API. This has been updated in doorbot https://github.com/davglass/doorbot/issues/16

**Comment by smileymiley** [comment]
Ah, I just installed to get events from the doorbell and hit the same issue! As benfysh mentioned above doorbot has some info on what Ring changed.  It would be really helpful if the code could be updated to get it working again. Thanks.

**Comment by will-austin** [comment]
I'm no longer having issues, I was able to pull back data as recently as this morning. What error are you getting?

**Comment by WeldFire** [comment]
@will-austin I'm getting the same issue and was actually about to work on trying to fix this.

I'm getting the following:
> Error: problem getting token for user \*\*\*\*@****.com from URL https://api.ring.com/clients_api/session Request failed with status code 401 :: Error: Request failed with status code 401

Your's works fine?

**Comment by smileymiley** [comment]
Same:
Error: problem getting token for user xxxx@gmail.com from URL https://api.ring.com/clients_api/session Request failed with status code 401 :: Error: Request failed with status code 401

I'm just using the example, as this is my first try with ring.  I altered only the first part to add credentials:

const ringApi = require( './node_modules/ring-api' )
const ring = ringApi({
    email: 'myemail@gmail.com',
    password: 'mypassword'
})

It seems to be picking up the credentials ok, as my correct email appears in the error message.
Thanks

**Comment by will-austin** [comment]
Hold up. I'm sorry, I went back and looked at my dev notes... I've had a lot going on at work lately and I'd forgotten a late night update to https://github.com/tchellomello/python-ring-doorbell... The problem is the method of authentication Ring recently updated. That package has the new authentication baked in.

**Comment by jimhigson** [comment]
I should have some time to look into this, thanks for bearing with in the meantime

**Comment by jimhigson** [comment]
Try using ring-api@2.1.0 now, this should be working again

**Comment by smileymiley** [comment]
Works for me! Many thanks :)

**Comment by TheOriginalMrWolf** [comment]
Hi,

Has this update been pushed to NPM (currently 3.0.3)?  I can't authenticate using the node-red-contrib-ringdoorbell wrapper -- and I guess 2.1.0 fixes it???

Error I get:
```
Error: session failed to initialise, cannot create ring-api instance --caused-by-> could not get auth token for user <<my user name>> --caused-by-> Request to ring API at https://oauth.ring.com/oauth/token failed with "The client is not authorized to request a token using this method." --caused-by-> Request failed with status code 401
```
...or is this now a new error??

Thanks!!!
