### ISSUE TITLE
Can't obtain oauth token - client not authorised

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [jimhigson/ring-api#9]
Hi,

I'm using the node-red-contrib-ringdoorbell wrapper which uses this library to connect to the ring api.

Getting the following when I try to connect:
```
Error: session failed to initialise, cannot create ring-api instance --caused-by-> could not get auth token for user <<my user name>> --caused-by-> Request to ring API at https://oauth.ring.com/oauth/token failed with "The client is not authorized to request a token using this method." --caused-by-> Request failed with status code 401
```

Are you aware of this issue?

Thanks!!!

**Comment by TheOriginalMrWolf** [comment]
Same, of course, if I just use ring-api directly.  Seems like Ring have changed something???

**Comment by jimhigson** [comment]
Getting the same - will have a fix soon

**Comment by jimhigson** [comment]
Looks like they're getting a lot tighter on the user agents they'll accept - this is no longer an option and I've changed the defaults

**Comment by TheOriginalMrWolf** [comment]
Awesome - thanks!!

**Comment by TheOriginalMrWolf** [comment]
Yep - just tried the example and it worked perfectly.  Many thanks!!!
